config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_name: {sign_in: "login", sign_out: "logout"}

  root :to => "application#index"

  resources :contacts
  resources :messages
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :user 
  has_many :messages 

  validates :user_id, presence: true 
  validates :full_name, presence: true 
  validates :phone_number, presence: true 
  validates :address, presence: true 

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user 
  belongs_to :contact 

  validates :contact_id, presence: true 
  validates :user_id, presence: true 
  validates :body, presence: true 
  validates :status, presence: true 

  before_create :send_message

private

  def send_message
    begin 
      response = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.twilio.com/2010-04-01/Accounts/AC57ab5b95dcf85a7dbd70f84a82417deb/Messages.json',
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
        ).execute
    rescue 
      false
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :messages
  has_many :contacts 

  validates :email, presence: true 
  validates :phone, presence: true 
  validates :password, presence: true 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    render 'index'
  end

protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone 
  end  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @contacts = Contact.all
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all 
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message has been saved."
      redirect_to messages_path
    else
      flash[:alert] = "Your message failed to send."
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div class="welcome">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="headline">
          <h1>Welcome to 'Texting'</h1>
          <p class="lead">A social texting app</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<h1>Address Book</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0px">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Internet Texting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="/messages">Inbox</a></li>
        <li><a href="/contacts">Address Book</a></li>
        <li><a href="#">Add New Contacts</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li style="top: 16px">Logged in as <strong><%= current_user.email %></strong>.</li>
          <li><%= link_to "Edit profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %> </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Internet Texting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
</head>
<body class="body">

  <%= render('layouts/navbar.html.erb') %>
  <div class="container"> 
    <%= flash[:notice] %>
    <%= flash[:alert] %> 

    <%= yield %>
  </div>

</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>
<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.id, message_path(message) %></li>

  <% end %>
</ul>


<%= link_to "New Message", new_message_path %> 

app/views/messages/new.html.erb
<div class="container"> 

  <h1>New Message</h1> 

  <% if @message.errors.any? %> 
    <p>Something went wrong:</p>
    <ul> 
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
    </ul> 
  <% end %> 


  <%= form_for @message do |f| %> 
    <div class="form-group"> 
      <%= f.label :to %> 
      <%= f.text_field :to %>
    </div>
    <div class="form-group">
      <%= f.label :from %> 
      <%= f.text_field :from %>
    </div>
    <div class="form-group"> 
      <%= f.label :body %>  
      <%= f.text_field :body %> 
    </div>
    <div><%= f.submit %></div> 
  <% end %> 

</div> 